---
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm64

clone:
  skip_verify: true

workspace:
  base: /go
  path: src/github.com/fuzzy/repetier

steps:
- name: test
  image: golang:alpine
  commands:
  - apk update
  - apk add make
  - make test
