---
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm64

clone:
  skip_verify: true

steps:
- name: test
  image: golang:alpine
  commands:
  - apk update
  - apk add make alpine-sdk
  - make test
